language: python

os:
    - linux

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python3
      - gcc
      - g++
      - pkg-config
      - gdb
      - python3-pip
      - pylint
      - git
      - cmake
      - libglib2.0-dev

before_script:
  - pip3 install --user --upgrade ropper retdec-python keystone-engine capstone unicorn
  - echo "source `pwd`/gef.py" > ~/.gdbinit

script:
  - gdb -q -ex 'gef help' -ex 'gef config' -ex 'quit' /bin/ls
  - python3 ./tests/test-runner.py

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat
    on_success: change
    on_failure: always
